<a href="https://colab.research.google.com/github/seannebue/Linear-Algebra-58019/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  #Import Library

from numpy.linalg import eig

In [2]:
A = np.array([[-12, 3],[4, 1]]) #matrix A
print(f'Matrix A:\n {A}') #print matrix A

inv_A = np.linalg.inv(A)  #inverse of matrix A
print(f'\nInverse of Matrix A:\n{inv_A}') #print inverse of matrix A

B = np.array([[0],[0]]) #matrix B
print(f'\nMatrix B:\n {B}') #print matrix B

X = np.dot(inv_A, B) #dot product of inverse matrix A and matrix B
print(f'\nDot product:\n{X}') #print dot product - wrong

Matrix A:
 [[-12   3]
 [  4   1]]

Inverse of Matrix A:
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]

Matrix B:
 [[0]
 [0]]

Dot product:
[[0.]
 [0.]]


Example 2

In [3]:
A = np.array([[-6,3],[4,5]]) #matrix
print(f'Matrix A:\n{A}') #print/display

w,v = np.linalg.eig(A) # use the eig method in order to get the eigenvalue and eigenvector of a square matrix A

#print/display the eigenvalues and eigenvectors
print(f'The eigenvalue/s is/are:\n {w}')
print(f'The right eigenvectors are:\n {v}')

Matrix A:
[[-6  3]
 [ 4  5]]
The eigenvalue/s is/are:
 [-7.  6.]
The right eigenvectors are:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


Example 1

In [4]:
A = np.array([[2,2,4],[1,3,5],[2,3,4]]) #matrix A
print(A) #print/display
s,t = np.linalg.eig(A) #eig method to get the eigenvalue and eigenvector of square matrix A

#print/display eigenvalues and eigenvectors
print(f'\nThe Eigenvalue/s is/are: {s.round()}')
print(f'\nThe right Eigenvectors are: \n{t.round()}\n')

c = np.dot(A,t.round()) #dot product of A and t
print(c) #print/display

[[2 2 4]
 [1 3 5]
 [2 3 4]]

The Eigenvalue/s is/are: [ 9.  1. -1.]

The right Eigenvectors are: 
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
