<a href="https://colab.research.google.com/github/seannebue/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [15]:
eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]]) #matrix 1
eq2 = np.array([[89],[89],[95]]) #matrix 2
amt = np.linalg.inv(eq1).dot(eq2) #compute using dot product
print(amt) #print/display

[[13.]
 [57.]
 [19.]]


Problem 2

In [17]:
import numpy as np 

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #matrix A
print(A)
print()

B = np.array([[5],[15],[-20]]) #matrix B
print(B)
print()

#inverse of A
#if np.linalg.inv is used, an error message will show up saying it is a singular matrix whose determinant is 0
#any 0 determinant cannot be solved due because its irreversible 
Apinv = np.linalg.pinv(A) #compute inverse of A

x = Apinv.dot(B) #dot product method
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

[[  5]
 [ 15]
 [-20]]

[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3

In [3]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A)

print("Eigenvalues are \n ",w)
print("Eigenvectors are \n ",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

Eigenvalues are 
  [-1.  3.  2.]
Eigenvectors are 
  [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
