<a href="https://colab.research.google.com/github/seannebue/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)**

In [8]:
import numpy as np 

SquareMatrix = np.array ([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) #5x5 matrix

print("This is an example of square matrix whose length is 5") 
print() 
print(SquareMatrix) #final answer

This is an example of square matrix whose length is 5

[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


**Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)**

In [19]:
C = np.triu([[10,20,30,40,50], [60,70,80,90,100],[110,120,130,140,150],[160,170,180,190,200],[210,220,230,240,250]])

print(C)

[[ 10  20  30  40  50]
 [  0  70  80  90 100]
 [  0   0 130 140 150]
 [  0   0   0 190 200]
 [  0   0   0   0 250]]


**Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)**

In [22]:
a = np.array([[1,2,3], [4,5,6], [7,8,9,]])
print(a)

b = np.transpose(a)
print()
print(b)

c = np.matmul(a,b)
print()
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


**Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)**

In [21]:
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])
print(C)
print()

invC = np.linalg.inv(C)
print("Inverse of Matrix C:")
print()
print(invC)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

Inverse of Matrix C:

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


**Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)**

In [12]:
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print()
print(int(detOfC))

Determinant of the given matrix in Question 4:

5


**Question 6. Find the roots of the linear equations by showing its python codes (30 points)**

In [16]:
import numpy as np
A = np.array([[5,4,1],[10,9,4],[10,13,15]]) #matrix A

print(A)
print()

inv_A = np.linalg.inv(A)
print(inv_A)
print()

B = np.array([[3.4],[8.8],[19.2]]) #matrix B

print(B)
print()
print("The roots of the given linear equations are" )
print()

X = np.dot(inv_A, B)
print(X)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]

[[ 3.4]
 [ 8.8]
 [19.2]]

The roots of the given linear equations are

[[0.2]
 [0.4]
 [0.8]]
