<a href="https://colab.research.google.com/github/seannebue/Linear-Algebra-58019/blob/main/Phyton_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vector Space Operations

Representing Vectors

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [ 2 -5]


Describing Vectors in Numpy

In [2]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [3]:
U = np.array([[1,2,3],[4,5,6,]])
U
U.size

6

# Space

**Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear eqautions.**

Additon of Vectors

In [4]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [5]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

Subtraction of Vector

In [6]:
#You will subtract the components of adden2 from adden1:adden1-adden2
difference = addend1-addend2
difference

array([-1, -1,  0])

In [7]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

Scalling

In [8]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

Cross Product

In [9]:
import numpy as np
A = np.array([2,3,4])
B = np.array([1,7,1])
output = np.cross(A,B)
print (output)

[-25   2  11]


In [10]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])
dot = np.dot(A,B)
print(dot)

23
