<a href="https://colab.research.google.com/github/seannebue/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 1

In [3]:
import numpy as np

A = np.array ([[1,2,3],[4,5,6]])
print("A =", A)
print()

B = np.array ([[1,2],[3,3],[5,6]])
print("B =", B)
print()

C = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print("C =", C)
print()

D = np.array ([[1,2],[3,4]])
print("D =", D)
print()

print("Examples")
print()

dot = np.dot(A,B)
print("a. AB =", A)
print()

sum = D+D
print("b. D + D =", A)
print()

S = 2*C
print("c. 2C =", S)

A = [[1 2 3]
 [4 5 6]]

B = [[1 2]
 [3 3]
 [5 6]]

C = [[1 2 3]
 [4 5 6]
 [7 8 9]]

D = [[1 2]
 [3 4]]

Examples

a. AB = [[1 2 3]
 [4 5 6]]

b. D + D = [[1 2 3]
 [4 5 6]]

c. 2C = [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Problem 2

In [5]:
import numpy as np
A = np.array([5,3,-1])

print("Size of Array:", A.size)
print("Type of Array:", type(A))
print("Shape of Array:", A.shape)
print("Dimension of Array:", A.ndim)


Size of Array: 3
Type of Array: <class 'numpy.ndarray'>
Shape of Array: (3,)
Dimension of Array: 1
