<a href="https://colab.research.google.com/github/seannebue/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1

In [7]:
import numpy as np

c = np.eye(4)

print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Question 2

In [8]:
import numpy as np

c = np.eye(4)

#solution that doubles the values
print(c*2)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


# Question 3

In [11]:
import numpy as np

a = np.array([2,7,4])
b = np.array([3,9,8])

#cross product of a and b
cross = np.cross(a,b)
print(cross)

[20 -4 -3]
